routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',
            ['uses' => 'HomeController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

//Asset
/*
Route::get('assets',
            ['uses' => 'AssetController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::get('assets/create',
            ['uses' => 'AssetController@create',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::post('assets',
            ['uses' => 'AssetController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::get('assets/{asset}',
            ['uses' => 'AssetController@show',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ])->name('assets.show');

Route::get('assets/{asset}/edit',
            ['uses' => 'AssetController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('assets.edit');

Route::patch('assets/{asset}',
            ['uses' => 'AssetController@update',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ]);

Route::delete('assets/{asset}',
            ['uses' => 'AssetController@destroy',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('assets.destroy');

Route::get('assets/{asset}/tag',
            ['uses' => 'AssetController@tag',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('tag');

Route::get('assets/{asset}/untag',
            ['uses' => 'AssetController@untag',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('untag');

Route::get('/asset_export', 'AssetController@export');
Route::get('/barcode-pdf','AssetController@generatePDF');
*/

//User
Route::get('users',
            ['uses' => 'UserController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::get('users/create',
            ['uses' => 'UserController@create',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::post('users',
            ['uses' => 'UserController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::get('users/{user}',
            ['uses' => 'UserController@show',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.show');

Route::get('users/{user}/edit',
            ['uses' => 'UserController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.edit');

Route::patch('users/{user}',
            ['uses' => 'UserController@update',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::delete('users/{user}',
            ['uses' => 'UserController@destroy',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.destroy');

Route::get('/user_search',
        ['uses' => 'UserController@search',
        'middleware' => ['auth', 'roles'],
        'roles' => ['Super User']
        ]);

//Location
/*
Route::get('location',
            ['uses' => 'LocationController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.index');

Route::get('location/{id}',
            ['uses' => 'LocationController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.edit');

Route::post('locations/create',
            ['uses' => 'LocationController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.store');

//Department
Route::get('department',
            ['uses' => 'DepartmentController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);
 */

Route::resource('location','LocationController');
Route::resource('department','DepartmentController');

Route::resource('itemlist','ItemListController');
Route::get('/itemreport','ItemListController@itemReport')->name('itemreport');
Route::resource('itemcategory','ItemCategoryController');
Route::resource('itemdetail','ItemDetailController');

Route::resource('employee','EmployeeController');
Route::resource('asset','AssetController');
Route::get('/print/{code}','AssetController@print')->name('print');
Route::get('/assetreport','AssetController@assetReport')->name('assetreport');

Route::get('employee/{id}/remove',
            ['uses' => 'EmployeeController@deleteEmployee',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('employee.remove');

Route::get('itemcategory/{id}/remove',
            ['uses' => 'ItemCategoryController@deleteItemCategory',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

Route::get('location/{id}/remove',
            ['uses' => 'LocationController@deleteLocation',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

Route::get('department/{id}/remove',
            ['uses' => 'DepartmentController@deleteDepartment',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

//Authentication
Auth::routes();


Route::view('/ar', 'report.ar')->name('ar');

//Home
Route::get('/home', 'HomeController@index')->name('home');


//Error Message
Route::get('errormessage', function(){
    return view('messages.error');
})->middleware('auth');

resources/views/assets_1/index.blade.php
@extends('layout')
@section('content')

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex">
                    <i class="mdi mdi-home text-muted hover-cursor"></i>
                    <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;</p>
                    <p class="text-primary mb-0 hover-cursor">Asset</p>
                </div>
                <br>
                

                <form action="{{ URL::to('asset/create') }}" method="GET">
                    <button type="submit" class="btn btn-inverse-primary btn-rounded btn-icon">
                        <i class="mdi mdi-database-plus"></i>
                    </button>
                </form>

                <div class="table-responsive pt-3">
                    <table id="dtBasicExample" class="table table-striped table-bordered display nowrap" cellspacing="0" width="100%">
                        <thead>
                          <tr>
                            <th class="th-sm">#</th>
                            <th class="th-sm">Asset Code</th>
                            <th class="th-sm">Employee Code</th>
                            <th width="th-sm">Item Code</th>
                            <th width="th-sm">Level</th>
                            <th width="th-sm">Transaction Type</th>
                            <th width="th-sm">Date Created</th>
                            <th width="th-sm">Last Update</th>
                            <th class="280px">Action</th>
                          </tr>
                        </thead>
                        <tbody>

                        </tbody>
                        <tfoot>
                          <tr>
                            <th class="th-sm">#</th>
                            <th class="th-sm">Asset Code</th>
                            <th class="th-sm">Employee Code</th>
                            <th width="th-sm">Item Code</th>
                            <th width="th-sm">Level</th>
                            <th width="th-sm">Transaction Type</th>
                            <th width="th-sm">Date Created</th>
                            <th width="th-sm">Last Update</th>
                            <th class="280px">Action</th>
                          </tr>
                        </tfoot>
                      </table>
                </div>

                <div class="modal fade" id="ajaxModel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="alert alert-danger" style="display:none"></div>
                            <div class="modal-header">
                                <h4 class="modal-title" id="modelHeading"></h4>
                            </div>


                            <div class="card-body">
                                <form id="LocationForm" name="LocationForm" class="form-horizontal">
                                    <input type="hidden" name="id" id="id">
                                    <input type="hidden" name="status" id="status">
                                    <input type="hidden" name="temp" id="temp">

                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Code<code>*</code></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="location_code" class="form-control" id="location_code" placeholder="Location Code Here">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Name<code>*</code></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="location_name" class="form-control" id="location_name" placeholder="Location name Here">
                                        </div>
                                    </div>

                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection


@push('scripts')
    <script>
        $(document).ready(function () {


            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $('#dtBasicExample tfoot th').not(":eq(8), :eq(0)").each( function () {
                var title = $(this).text();
                $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
            } );

            var table = $('#dtBasicExample').DataTable({
                select: true,
                processing: true,
                serverSide: true,
                ajax: {
                    'url':"{{ route('asset.index') }}",
                    'type': 'GET',
                    'headers': {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                },

                orderCellsTop: true,
                fixedHeader: true,
                columns: [
                        {data: 'id', name: 'id'},
                        {data: 'code', name: 'code'},
                        {data: 'employee_code', name: 'employee_code'},
                        {data: 'item_code', name: 'item_code'},
                        {data: 'level', name: 'level'},
                        {data: 'transaction_type', name: 'transaction_type'},
                        {data: 'created_at', name: 'created_at'},
                        {data: 'updated_at', name: 'updated_at'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ],
            order: [[0, 'desc']]
            });


        });
    </script>
@endpush