routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',
            ['uses' => 'HomeController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

//Asset
/*
Route::get('assets',
            ['uses' => 'AssetController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::get('assets/create',
            ['uses' => 'AssetController@create',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::post('assets',
            ['uses' => 'AssetController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::get('assets/{asset}',
            ['uses' => 'AssetController@show',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ])->name('assets.show');

Route::get('assets/{asset}/edit',
            ['uses' => 'AssetController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('assets.edit');

Route::patch('assets/{asset}',
            ['uses' => 'AssetController@update',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ]);

Route::delete('assets/{asset}',
            ['uses' => 'AssetController@destroy',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('assets.destroy');

Route::get('assets/{asset}/tag',
            ['uses' => 'AssetController@tag',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('tag');

Route::get('assets/{asset}/untag',
            ['uses' => 'AssetController@untag',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('untag');

Route::get('/asset_export', 'AssetController@export');
Route::get('/barcode-pdf','AssetController@generatePDF');
*/

//User
Route::get('users',
            ['uses' => 'UserController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::get('users/create',
            ['uses' => 'UserController@create',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::post('users',
            ['uses' => 'UserController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::get('users/{user}',
            ['uses' => 'UserController@show',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.show');

Route::get('users/{user}/edit',
            ['uses' => 'UserController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.edit');

Route::patch('users/{user}',
            ['uses' => 'UserController@update',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::delete('users/{user}',
            ['uses' => 'UserController@destroy',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.destroy');

Route::get('/user_search',
        ['uses' => 'UserController@search',
        'middleware' => ['auth', 'roles'],
        'roles' => ['Super User']
        ]);

//Location
/*
Route::get('location',
            ['uses' => 'LocationController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.index');

Route::get('location/{id}',
            ['uses' => 'LocationController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.edit');

Route::post('locations/create',
            ['uses' => 'LocationController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.store');

//Department
Route::get('department',
            ['uses' => 'DepartmentController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);
 */

Route::resource('location','LocationController');
Route::resource('department','DepartmentController');

Route::resource('itemlist','ItemListController');
Route::get('/itemreport','ItemListController@itemReport')->name('itemreport');
Route::resource('itemcategory','ItemCategoryController');
Route::resource('itemdetail','ItemDetailController');

Route::resource('employee','EmployeeController');
Route::resource('asset','AssetController');
Route::get('/print/{code}','AssetController@print')->name('print');
Route::get('/assetreport','AssetController@assetReport')->name('assetreport');

Route::get('employee/{id}/remove',
            ['uses' => 'EmployeeController@deleteEmployee',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('employee.remove');

Route::get('itemcategory/{id}/remove',
            ['uses' => 'ItemCategoryController@deleteItemCategory',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

Route::get('location/{id}/remove',
            ['uses' => 'LocationController@deleteLocation',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

Route::get('department/{id}/remove',
            ['uses' => 'DepartmentController@deleteDepartment',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

//Authentication
Auth::routes();


Route::view('/ar', 'report.ar')->name('ar');

//Home
Route::get('/home', 'HomeController@index')->name('home');


//Error Message
Route::get('errormessage', function(){
    return view('messages.error');
})->middleware('auth');

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $guarded = [];
    public $table = "departments";
    protected $fillable = ['id', 'code', 'name', 'location_id', 'is_deleted', 'created_at', 'updated_at'];
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use DB;
use DataTables;
use Alert;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$data = Department::where('is_deleted', '<>', '1')->orderBy('id', 'ASC')->get();
        $data = DB::table('departments')
                ->join('locations', 'locations.id', '=', 'departments.location_id')
                ->select('departments.id as id', 'departments.code as deptcode', 'departments.name as deptname',
                        'locations.name as locname', 'departments.created_at as created_at', 'departments.updated_at as updated_at')
                ->where('departments.is_deleted', '<>', '1')->orderBy('departments.id', 'ASC')->get();

        $locations = DB::table('locations')
                ->select('id', 'code', 'name')
                ->where('is_deleted', '<>', '1')->orderBy('name', 'ASC')->get();

        if (request()->ajax()){
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){

                    $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editDepartment">Edit</a>';

                    $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteDepartment">Delete</a>';

                        return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('settings.department.index', compact('locations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'department_code' => 'required|min:2',
            'department_name' => 'required|min:3',
            'location' => 'required',
        ]);

            if ($validator->fails())
            {
                return response()->json(['errors'=>$validator->errors()->all()]);
            }

            if($request->status == "create"){
                if(Department::where([
                                    ['code', '=', $request->department_code],
                                    ['location_id', '=', $request->location],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                                        return response()->json(['code'=>'1']);
                }else{
                    Department::updateOrCreate(['id' => $request->id],
                                                ['code' => $request->department_code,
                                                'name' => $request->department_name,
                                                'location_id' => $request->location,
                                                'is_deleted' => '0']);
                }
            }elseif($request->status == "edit"){
                if(Department::where([
                                    ['id', '=', Input::get('id')],
                                    ['code', '=', Input::get('department_code')],
                                    ['location_id', '=', Input::get('location')],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                                        Department::find(Input::get('id'))
                                                    ->update(['name' => $request->department_name,
                                                            'location_id' => $request->location,
                                                            'is_deleted' => '0']);
                }else{
                    if(Department::where([
                                        ['code', '=', Input::get('department_code')],
                                        ['location_id', '=', Input::get('location')],
                                        ['is_deleted', '<>', '1']
                                        ])->exists()){
                                            return response()->json(['code'=>'1']);
                    }else{
                        Department::find(Input::get('id'))
                                        ->update(['code' => $request->department_code,
                                                'name' => $request->department_name,
                                                'location_id' => $request->location,
                                                'is_deleted' => '0']);
                    }
                    
                }
            }

        return response()->json(['success'=>$request->status]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //$location = Location::find($id);
        $data = DB::table('departments')
                ->join('locations', 'locations.id', '=', 'departments.location_id')
                ->select('departments.id as id', 'departments.code as deptcode', 'departments.name as deptname',
                        'locations.id as locid', 'departments.created_at as created_at', 'departments.updated_at as updated_at')
                ->where('departments.is_deleted', '<>', '1')
                ->where('departments.id', '=', $id)->orderBy('departments.id', 'ASC')->get();

        return response()->json($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Department $department)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        //
    }

    public function deleteDepartment($id)
    {
        Department::updateOrCreate(['id' => $id],
                                    ['is_deleted' => '1']);

        return response()->json(['successfully deleted']);
    }
}

resources/views/settings/department/index.blade.php
@extends('layout')
@section('content')

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex">
                    <i class="mdi mdi-home text-muted hover-cursor"></i>
                    <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Settings&nbsp;/&nbsp;</p>
                    <p class="text-primary mb-0 hover-cursor">Department</p>
                </div>
                <br>
                <button type="button" class="btn btn-inverse-primary btn-rounded btn-icon" id="createDepartment">
                    <i class="mdi mdi-database-plus"></i>
                </button>

                <div class="table-responsive pt-3">
                    <table id="dtBasicExample" class="table table-striped table-bordered display nowrap" cellspacing="0" width="100%">
                        <thead>
                          <tr>
                            <th class="th-sm">#</th>
                            <th class="th-sm">Code</th>
                            <th class="th-sm">Name</th>
                            <th class="th-sm">Location</th>
                            <th class="th-sm">Date Created</th>
                            <th class="th-sm">Last Update</th>
                            <th class="th-sm">Action</th>
                          </tr>
                        </thead>
                        <tbody>

                        </tbody>
                        <tfoot>
                            <tr>
                                <th class="th-sm">#</th>
                                <th class="th-sm">Code</th>
                                <th class="th-sm">Name</th>
                                <th class="th-sm">Location</th>
                                <th class="th-sm">Date Created</th>
                                <th class="th-sm">Last Update</th>
                                <th class="th-sm">Action</th>
                            </tr>
                        </tfoot>
                      </table>
                </div>

                <div class="modal fade" id="ajaxModel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="alert alert-danger" style="display:none"></div>
                            <div class="modal-header">
                                <h4 class="modal-title" id="modelHeading"></h4>
                            </div>


                            <div class="card-body">
                                <form id="LocationForm" name="LocationForm" class="form-horizontal">
                                    <input type="hidden" name="id" id="id">
                                    <input type="hidden" name="status" id="status">

                                    <div class="form-group row">
                                        <label for="code" class="col-sm-3 text-right control-label col-form-label">Code<code>*</code></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="department_code" class="form-control" id="department_code" placeholder="Department Code Here">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="name" class="col-sm-3 text-right control-label col-form-label">Name<code>*</code></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="department_name" class="form-control" id="department_name" placeholder="Department name Here">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="location" class="col-sm-3 text-right control-label col-form-label">Location<code>*</code></label>
                                        <div class="col-sm-9">
                                            <select id="location" name="location" class="selectpicker" data-live-search="true" class="selectpicker show-tick">
                                                @foreach($locations as $location)
                                                    <option value={{ $location->id }}>{{ $location->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection


@push('scripts')
    <script>
        $(document).ready(function () {

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('#dtBasicExample').DataTable({
                select: true,
                processing: true,
                serverSide: true,
                ajax: {
                    'url':"{{ route('department.index') }}",
                    'type': 'GET',
                    'headers': {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                },

                orderCellsTop: true,
                fixedHeader: true,
                columns: [
                        {data: 'id', name: 'id'},
                        {data: 'deptcode', name: 'deptcode'},
                        {data: 'deptname', name: 'deptname'},
                        {data: 'locname', name: 'locname'},
                        {data: 'created_at', name: 'created_at'},
                        {data: 'updated_at', name: 'updated_at'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ],
            order: [[0, 'desc']]
            });

            $('#createDepartment').click(function () {
                $('#saveBtn').val("create-department");
                $('#id').val('');
                $('#status').val('create');
                $('#LocationForm').trigger("reset");
                $('#modelHeading').html("Create New Department");
                $('#ajaxModel').modal('show');
                $('.alert-danger').hide();
            });

            $('body').on('click', '.editDepartment', function () {
                var department_id = $(this).data('id');

                $.get("{{ route('department.index') }}" +'/' + department_id +'/edit', function (data) {
                    $('#modelHeading').html("Edit Department");
                    $('#status').val('edit');
                    $('#saveBtn').val("edit-department");
                    $('#ajaxModel').modal('show');
                    $('#saveBtn').html('Save changes');
                    $('#id').val(data[0].id);
                    $('#department_code').val(data[0].deptcode);
                    $('#department_name').val(data[0].deptname);
                    $('#location').val(data[0].locid);
                })
            });

            $('#saveBtn').click(function (e) {
                e.preventDefault();
                $(this).html('Sending..');
                $('.alert-danger').hide();
                
                $.ajax({
                data: $('#LocationForm').serialize(),
                url: "{{ route('department.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {
                    if(data.errors){
                        $('.alert-danger').html('');
                        $('#saveBtn').html('Save changes');
                        $.each(data.errors, function(key, value){
                            $('.alert-danger').show();
                            $('.alert-danger').append('<li>'+value+'</li>');
                  		});

                  	}else if(data.code == "1"){
                        $('.alert-danger').html('');
                        $('#saveBtn').html('Save changes');
                        $('.alert-danger').show();
                        $('.alert-danger').append('<li>Department Code Already Exists</li>');
                    }else{
                        $('#LocationForm').trigger("reset");
                        $('#ajaxModel').modal('hide');
                        $('.alert-danger').hide();
                        $('#saveBtn').html('Save changes');
                        table.draw();
                  	}

                },
                error: function (data) {
                    console.log('Error:', data);
                    jQuery('#saveBtn').html('Save Changes');
                }
                });
            });

            $('body').on('click', '.deleteDepartment', function (){
                var id = $(this).data("id");


                swal({
                    title: "Do you want to delete this department?",
                    text: "You will not be able to recover this department!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn btn-success",
                    cancelButtonClass: 'btn btn-danger',
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel please!",
                    },
                    function(isConfirm) {
                        if (isConfirm) {
                            $.ajax({
                                type: "GET",
                                url: "{{ route('department.index') }}" +'/' + id +'/remove',
                                success: function(data){
                                    swal("Deleted!", "Department has been deleted.", "success");
                                    table.draw();
                                },
                                error: function(data){
                                    console.log('Error', data);
                                }
                            });
                        } else {
                            swal("Cancelled", "Your imaginary file is safe :)", "error");
                        }
                });

           });

        });
    </script>
@endpush