routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',
            ['uses' => 'HomeController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

//Asset
/*
Route::get('assets',
            ['uses' => 'AssetController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::get('assets/create',
            ['uses' => 'AssetController@create',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::post('assets',
            ['uses' => 'AssetController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ]);

Route::get('assets/{asset}',
            ['uses' => 'AssetController@show',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff', 'Staff']
            ])->name('assets.show');

Route::get('assets/{asset}/edit',
            ['uses' => 'AssetController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('assets.edit');

Route::patch('assets/{asset}',
            ['uses' => 'AssetController@update',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ]);

Route::delete('assets/{asset}',
            ['uses' => 'AssetController@destroy',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('assets.destroy');

Route::get('assets/{asset}/tag',
            ['uses' => 'AssetController@tag',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('tag');

Route::get('assets/{asset}/untag',
            ['uses' => 'AssetController@untag',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User', 'Head Staff']
            ])->name('untag');

Route::get('/asset_export', 'AssetController@export');
Route::get('/barcode-pdf','AssetController@generatePDF');
*/

//User
Route::get('users',
            ['uses' => 'UserController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::get('users/create',
            ['uses' => 'UserController@create',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::post('users',
            ['uses' => 'UserController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::get('users/{user}',
            ['uses' => 'UserController@show',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.show');

Route::get('users/{user}/edit',
            ['uses' => 'UserController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.edit');

Route::patch('users/{user}',
            ['uses' => 'UserController@update',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);

Route::delete('users/{user}',
            ['uses' => 'UserController@destroy',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('users.destroy');

Route::get('/user_search',
        ['uses' => 'UserController@search',
        'middleware' => ['auth', 'roles'],
        'roles' => ['Super User']
        ]);

//Location
/*
Route::get('location',
            ['uses' => 'LocationController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.index');

Route::get('location/{id}',
            ['uses' => 'LocationController@edit',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.edit');

Route::post('locations/create',
            ['uses' => 'LocationController@store',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.store');

//Department
Route::get('department',
            ['uses' => 'DepartmentController@index',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ]);
 */

Route::resource('location','LocationController');
Route::resource('department','DepartmentController');

Route::resource('itemlist','ItemListController');
Route::get('/itemreport','ItemListController@itemReport')->name('itemreport');
Route::resource('itemcategory','ItemCategoryController');
Route::resource('itemdetail','ItemDetailController');

Route::resource('employee','EmployeeController');
Route::resource('asset','AssetController');
Route::get('/print/{code}','AssetController@print')->name('print');
Route::get('/assetreport','AssetController@assetReport')->name('assetreport');

Route::get('employee/{id}/remove',
            ['uses' => 'EmployeeController@deleteEmployee',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('employee.remove');

Route::get('itemcategory/{id}/remove',
            ['uses' => 'ItemCategoryController@deleteItemCategory',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

Route::get('location/{id}/remove',
            ['uses' => 'LocationController@deleteLocation',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

Route::get('department/{id}/remove',
            ['uses' => 'DepartmentController@deleteDepartment',
            'middleware' => ['auth', 'roles'],
            'roles' => ['Super User']
            ])->name('location.remove');

//Authentication
Auth::routes();


Route::view('/ar', 'report.ar')->name('ar');

//Home
Route::get('/home', 'HomeController@index')->name('home');


//Error Message
Route::get('errormessage', function(){
    return view('messages.error');
})->middleware('auth');

app/ItemCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ItemCategory extends Model
{
    protected $guarded = [];
    public $table = "item_categories";
    protected $fillable = ['id', 'code', 'name', 'is_deleted', 'created_at', 'updated_at'];
}

app/Http/Controllers/ItemCategoryController.php
<?php

namespace App\Http\Controllers;

use App\ItemCategory;
use Illuminate\Support\Facades\Input;
use Illuminate\Http\Request;
use DataTables;

class ItemCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = ItemCategory::where('is_deleted', '<>', '1')->orderBy('id', 'ASC')->get();
        if (request()->ajax()){
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function($row){

                    $btn = '<a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="edit btn btn-primary btn-sm editItemCategory">Edit</a>';

                    $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger btn-sm deleteItemCategory">Delete</a>';

                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }

        return view('settings.item_category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'itemcategory_name' => 'required|min:3',
            'itemcategory_code' => 'required|min:3',
        ]);

        if ($validator->fails())
        {
            return response()->json(['errors'=>$validator->errors()->all()]);
        }

        if($request->status == "create"){
            if(ItemCategory::where([
                                    ['code', '=', Input::get('itemcategory_code')],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                return response()->json(['code'=>'1']);
            }else{
                ItemCategory::updateOrCreate(['id' => $request->id],
                                                            ['code' => $request->itemcategory_code,
                                                                'name' => $request->itemcategory_name,
                                                                'is_deleted' => '0']);
            }
        }elseif($request->status == "edit"){
            if(ItemCategory::where([
                                ['code', '=', Input::get('itemcategory_code')],
                                ['id', '=', Input::get('id')],
                                ['is_deleted', '<>', '1']
                                ])->exists()){
                                    ItemCategory::find(Input::get('id'))
                                            ->update(['name' => $request->itemcategory_name,
                                                    'is_deleted' => '0']);
            }else{
                if(ItemCategory::where([
                                    ['code', '=', Input::get('itemcategory_code')],
                                    ['id', '<>', Input::get('id')],
                                    ['is_deleted', '<>', '1']
                                    ])->exists()){
                                        return response()->json(['code'=>'1']);
                    }else{
                        ItemCategory::find(Input::get('id'))
                                            ->update(['code' => $request->itemcategory_code,
                                                    'name' => $request->itemcategory_name,
                                                    'is_deleted' => '0']);
                    }
            }
        }

        return response()->json(['success'=>$request->status]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ItemCategory  $itemCategory
     * @return \Illuminate\Http\Response
     */
    public function show(ItemCategory $itemCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ItemCategory  $itemCategory
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $itemcategory = ItemCategory::find($id);
        return response()->json($itemcategory);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ItemCategory  $itemCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ItemCategory $itemCategory)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ItemCategory  $itemCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(ItemCategory $itemCategory)
    {
        //
    }

    public function deleteItemCategory($id)
    {
        ItemCategory::updateOrCreate(['id' => $id],
                                    ['is_deleted' => '1']);

        return response()->json(['successfully deleted']);
    }
}

resources/views/settings/item_category/index.blade.php
@extends('layout')
@section('content')

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex">
                    <i class="mdi mdi-home text-muted hover-cursor"></i>
                    <p class="text-muted mb-0 hover-cursor">&nbsp;/&nbsp;Settings&nbsp;/&nbsp;</p>
                    <p class="text-primary mb-0 hover-cursor">Item Category</p>
                </div>
                <br>

                <button type="button" class="btn btn-inverse-primary btn-rounded btn-icon" id="createItemCategory">
                    <i class="mdi mdi-database-plus"></i>
                </button>

                <div class="table-responsive pt-3">
                    <table id="dtBasicExample" class="table table-striped table-bordered display nowrap" cellspacing="0" width="100%">
                        <thead>
                          <tr>
                            <th class="th-sm">#</th>
                            <th class="th-sm">Code</th>
                            <th class="th-sm">Name</th>
                            <th class="th-sm">Date Created</th>
                            <th class="th-sm">Last Update</th>
                            <th width="280px">Action</th>
                          </tr>
                        </thead>
                        <tbody>

                        </tbody>
                        <tfoot>
                          <tr>
                            <th class="th-sm">#</th>
                            <th class="th-sm">Code</th>
                            <th class="th-sm">Name</th>
                            <th class="th-sm">Date Created</th>
                            <th class="th-sm">Last Update</th>
                            <th width="280px">Action</th>
                          </tr>
                        </tfoot>
                      </table>
                </div>

                <div class="modal fade" id="ajaxModel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="alert alert-danger" style="display:none"></div>
                            <div class="modal-header">
                                <h4 class="modal-title" id="modelHeading"></h4>
                            </div>


                            <div class="card-body">
                                <form id="ItemCategoryForm" name="ItemCategoryForm" class="form-horizontal">
                                    <input type="hidden" name="id" id="id">
                                    <input type="hidden" name="status" id="status">

                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Code<code>*</code></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="itemcategory_code" class="form-control" id="itemcategory_code" placeholder="Item Category Code Here">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label for="lname" class="col-sm-3 text-right control-label col-form-label">Name<code>*</code></label>
                                        <div class="col-sm-9">
                                            <input type="text" name="itemcategory_name" class="form-control" id="itemcategory_name" placeholder="Item Category name Here">
                                        </div>
                                    </div>

                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-primary" id="saveBtn" value="create">Save changes</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection


@push('scripts')
    <script>
        $(document).ready(function () {


            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('#dtBasicExample').DataTable({
                select: true,
                processing: true,
                serverSide: true,
                ajax: {
                    'url':"{{ route('itemcategory.index') }}",
                    'type': 'GET',
                    'headers': {
                    'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                },

                orderCellsTop: true,
                fixedHeader: true,
                columns: [
                        {data: 'id', name: 'id'},
                        {data: 'code', name: 'code'},
                        {data: 'name', name: 'name'},
                        {data: 'created_at', name: 'created_at'},
                        {data: 'updated_at', name: 'updated_at'},
                        {data: 'action', name: 'action', orderable: false, searchable: false},
                    ],
            order: [[0, 'desc']]
            });

            $('#createItemCategory').click(function () {
                $('#saveBtn').val("create-itemcategory");
                $('#id').val('');
                $('#status').val('create');
                $('#ItemCategoryForm').trigger("reset");
                $('#modelHeading').html("Create New Item Category");
                $('#ajaxModel').modal('show');
                $('.alert-danger').hide();
            });

            $('body').on('click', '.editItemCategory', function () {
                var itemcategory_id = $(this).data('id');

                $.get("{{ route('itemcategory.index') }}" +'/' + itemcategory_id +'/edit', function (data) {
                    $('#modelHeading').html("Edit Item Category");
                    $('#status').val('edit');
                    $('#saveBtn').val("edit-itemcategory");
                    $('#ajaxModel').modal('show');
                    $('#saveBtn').html('Save changes');
                    $('#id').val(data.id);
                    $('#itemcategory_code').val(data.code);
                    $('#itemcategory_name').val(data.name);
                })
            });

            $('#saveBtn').click(function (e) {
                e.preventDefault();
                $(this).html('Sending..');
                $('.alert-danger').hide();
                
                $.ajax({
                data: $('#ItemCategoryForm').serialize(),
                url: "{{ route('itemcategory.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {
                    if(data.errors){
                        $('.alert-danger').html('');
                        $('#saveBtn').html('Save changes');
                        $.each(data.errors, function(key, value){
                            $('.alert-danger').show();
                            $('.alert-danger').append('<li>'+value+'</li>');
                  		});

                  	}else if(data.code == "1"){
                        $('.alert-danger').html('');
                        $('#saveBtn').html('Save changes');
                        $('.alert-danger').show();
                        $('.alert-danger').append('<li>Item Category Code Already Exists</li>');
                    }else{
                        $('#ItemCategoryForm').trigger("reset");
                        $('#ajaxModel').modal('hide');
                        $('.alert-danger').hide();
                        $('#saveBtn').html('Save changes');
                        table.draw();
                  	}

                },
                error: function (data) {
                    console.log('Error:', data);
                    jQuery('#saveBtn').html('Save Changes');
                }
                });
            });

            $('body').on('click', '.deleteItemCategory', function (){
                var id = $(this).data("id");


                swal({
                    title: "Do you want to delete this Item Category?",
                    text: "You will not be able to recover this Item Category!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonClass: "btn btn-success",
                    cancelButtonClass: 'btn btn-danger',
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel please!",
                    },
                    function(isConfirm) {
                        if (isConfirm) {
                            $.ajax({
                                type: "GET",
                                url: "{{ route('itemcategory.index') }}" +'/' + id +'/remove',
                                success: function(data){
                                    swal("Deleted!", "Item Category has been deleted.", "success");
                                    table.draw();
                                },
                                error: function(data){
                                    console.log('Error', data);
                                }
                            });
                        } else {
                            swal("Cancelled", "Your imaginary file is safe :)", "error");
                        }
                });

           });


        });
    </script>
@endpush